name = "recruitment-worker"
main = "src/index.ts"
compatibility_date = "2025-11-13"

[[d1_databases]]
binding = "DB"
database_name = "recruitment_db"
database_id = "c030e5bc-3c11-4ca3-9c2e-6db0d576f08d"
